name: BUILD-SEGA_SATURN-ROM

on:
  push:
    paths:
    - '.github/workflows/build-saturn-rom.yml'
    - '240psuite/Sarurn/**'
  pull_request:
    paths:
    - '.github/workflows/build-saturn-rom.yml'
    - '240psuite/Saturn/**'

jobs:
  build:
    if: ${{ false }}  # disable for now as unworking prototype.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install SDK
      run: |
        echo "TODO: this is currently based on libyaul, but is in an unworking state."

    - name: Build ROM
      working-directory: ${{ github.workspace }}/240psuite/Saturn/240psuite/
      env:
        INSTALL_ROOT: ${{ github.workspace }}/sdk
      run: |
        make

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: SEGA_SATURN-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/Saturn/*.COF
