name: BUILD-SEGA_DREAMCAST-ROM

on:
  push:
    paths:
    - '.github/workflows/build-dreamcast-rom.yml'
    - '240psuite/Dreamcast/**'
  pull_request:
    paths:
    - '.github/workflows/build-dreamcast-rom.yml'
    - '240psuite/Dreamcast/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install DreamSDK
      run: |
        # Download SDK
        curl -L https://www.dreamsdk.org/download/ --output DreamSDK-R2-Setup.exe
        # Install SDK silently
        .\DreamSDK-R2-Setup.exe /s


    - name: Build ROM
      working-directory: ${{ github.workspace }}/240psuite/Dreamcast/PVR/
      run: |
        make

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: SEGA_DREAMCAST-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/Dreamcast/*.GD-ROM
