name: BUILD-NINTENDO_64-ROM

on:
  push:
    paths:
    - '.github/workflows/build-n64-rom.yml'
    - '240psuite/N64/**'
  pull_request:
    paths:
    - '.github/workflows/build-n64-rom.yml'
    - '240psuite/N64/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/networkfusion/libdragon:win-cross-compile

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: source
        fetch-depth: 0
    - name: Checkout sdk repo
      uses: actions/checkout@v2
      with:
        repository: n64-tools/libdragon
        ref: '7f15d92134eb013634e0b079e5dd6e88ebca71dd'
        path: libdragon
        fetch-depth: 0

    - name: Adjust and re-build libdragon source
      run: |
        ls
        # Copy the adjusted source into the /libdragon folder
        cp -f ./source/240psuite/N64/libdragonchanges/display.c ./libdragon/src
        cp -f ./source/240psuite/N64/libdragonchanges/graphics.c ./libdragon/src
        cp -f ./source/240psuite/N64/libdragonchanges/display.h ./libdragon/include
        cp -f ./source/240psuite/N64/libdragonchanges/font.h ./libdragon/include
        echo "copy finished!"
        # Rebuild libdragon for changed source
        cd ./libdragon
        make libdragon
        make install
        # libdragon make
        # libdragon make install
        # libdragon make tools-install # the tools are default so commmented out.

    - name: Build ROM
      working-directory: ${{ github.workspace }}/source/240psuite/N64/
      run: |
        #libdragon make
        cd ./source/240psuite/N64/
        make

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_64-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/N64/*.z64
