name: BUILD-NINTENDO_SNES-ROM

on:
  push:
    paths:
    - '.github/workflows/build-snes-rom.yml'
    - '240psuite/SNES/**'
  pull_request:
    paths:
    - '.github/workflows/build-snes-rom.yml'
    - '240psuite/SNES/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    # - uses: msys2/setup-msys2@v2
    #   with:
    #     path-type: inherit
    #     update: true
    #     install: >-
    #       base-devel
    #       git

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout sdk repo
      uses: actions/checkout@v2
      with:
        # repository: ArtemioUrbina/pvsneslib-240ptestsuite-fork
        repository: alekmaul/pvsneslib
        ref: f128d1faab77250797057e936c14967c5380c7b4
        path: 240psuite/SNES/snesSDK/
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '2.7'

    - name: Setup SDK
      shell: bash
      working-directory: ${{ github.workspace }}/240psuite/SNES/snesSDK/devkitsnes/bin/
      run: |
        # convert line endings to unix
        sed -i -e 's/\r$//' 816-opt.py
        sed -i -e 's/^M$//' 816-opt.py
        # pythonLocation: C:\hostedtoolcache\windows\Python\2.7.18\x64
        sed -i -e 's+#!/c/Python27/python+#!"C:\hostedtoolcache\windows\Python\2.7.18\x64\python.exe"+' 816-opt.py
        chmod +rwx 816-opt.py


    - name: Build ROM
      # shell: msys2 {0}
      shell: cmd
      working-directory: ${{ github.workspace }}/240psuite/SNES/240pSuite
      env:
        DEVKITSNES: D:/a/240pTestSuite/240pTestSuite/240psuite/SNES/snesSDK
        DEVKIT65XX: D:/a/240pTestSuite/240pTestSuite/240psuite/SNES/snesSDK/devkitsnes
        DEVKIT65XX_WIN: D:\a\240pTestSuite\240pTestSuite\240psuite\SNES\snesSDK\devkitsnes
      run: |
        # echo "default path:"
        # echo $PATH
        # export PATH=D:/a/240pTestSuite/240pTestSuite/240psuite/SNES/snesSDK/devkitsnes/bin:$PATH
        # echo "new path:"
        # echo $PATH
        # echo "start build:"
        
        PATH %DEVKIT65XX_WIN%\bin;%PATH%
        # seems to require Python27 (not good!)
        make

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_SNES-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/SNES/**/*.SFC
