name: BUILD-NINTENDO_SNES-ROM

on:
  push:
    paths:
    - '.github/workflows/build-snes-rom.yml'
    - '240psuite/SNES/**'
  pull_request:
    paths:
    - '.github/workflows/build-snes-rom.yml'
    - '240psuite/SNES/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build ROM
      run: |
        cd ${{ github.workspace }}/240psuite/SNES/240pSuite
        make

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_SNES-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/SNES/*.SFC
