name: BUILD-SEGA_GENESIS-ROM

on:
  push:
    paths:
    - '.github/workflows/build-genesis-rom.yml'
    - '240psuite/Genesis/**'
  pull_request:
    paths:
    - '.github/workflows/build-genesis-rom.yml'
    - '240psuite/Genesis/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build ROM
      run: |
        cd ${{ github.workspace }}/240psuite/Genesis/240p/
        # TODO: Download SDK:
        # https://github.com/ArtemioUrbina/SGDK_1_11_Suite
        # TODO: Run Build file:
        # ???

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: SEGA_GENESIS-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/Genesis/*.GEN
