name: BUILD-NINTENDO_SNES-ROM

on:
  push:
    paths:
    - '.github/workflows/build-snes-rom.yml'
    - '240psuite/SNES/**'
  pull_request:
    paths:
    - '.github/workflows/build-snes-rom.yml'
    - '240psuite/SNES/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout sdk repo
      uses: actions/checkout@v2
      with:
        repository: ArtemioUrbina/pvsneslib-240ptestsuite-fork
        path: 240psuite/SNES/snesSDK/
        fetch-depth: 0

    - name: Check SDK install DIR
      working-directory: ${{ github.workspace }}/240psuite/SNES/snesSDK/
      run: |
        ls
        cd ./devkitsnes
        ls

    - name: Build ROM
      shell: cmd
      working-directory: ${{ github.workspace }}/240psuite/SNES/240pSuite/
      env:
        DEVKITSNES: D:/a/240pTestSuite/240pTestSuite/240psuite/SNES/snesSDK/
        DEVKIT65XX: D:/a/240pTestSuite/240pTestSuite/240psuite/SNES/snesSDK/devkitsnes
      run: |
        make

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_SNES-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/SNES/**/*.SFC
