name: BUILD-NINTENDO_64-ROM

on:
  push:
    paths:
    - '.github/workflows/build-n64-rom.yml'
    - '240psuite/N64/**'
  pull_request:
    paths:
    - '.github/workflows/build-n64-rom.yml'
    - '240psuite/N64/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: anacierdem/libdragon:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout sdk repo
      uses: actions/checkout@v2
      with:
        repository: dragonminded/libdragon
        path: libdragon
        fetch-depth: 0

    - name: Adjust and re-build libdragon source
      working-directory: ${{ github.workspace }}/libdragon/
      run: |
        # Copy the adjusted source into the ./libdragon folder
        cp -f ${{ github.workspace }}/240psuite/N64/libdragonchanges/display.c ${{ github.workspace }}/libdragon/src
        cp -f ${{ github.workspace }}/240psuite/N64/libdragonchanges/graphics.c ${{ github.workspace }}/libdragon/src
        cp -f ${{ github.workspace }}/240psuite/N64/libdragonchanges/display.h ${{ github.workspace }}/libdragon/include
        cp -f ${{ github.workspace }}/240psuite/N64/libdragonchanges/font.h ${{ github.workspace }}/libdragon/include
        # Rebuild libdragon for changed source
        libdragon make
        libdragon make install
        # libdragon make tools-install # the tools are default so commmented out.

    - name: Build ROM
      working-directory: ${{ github.workspace }}/240psuite/N64/
      run: |
        libdragon make

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_64-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/N64/*.z64
