name: BUILD-NINTENDO_64-ROM

on:
  push:
    paths:
    - '.github/workflows/build-n64-rom.yml'
    - '240psuite/N64/**'
  pull_request:
    paths:
    - '.github/workflows/build-n64-rom.yml'
    - '240psuite/N64/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/dragonminded/libdragon:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: source
        fetch-depth: 0
    - name: Checkout sdk repo
      uses: actions/checkout@v2
      with:
        repository: DragonMinded/libdragon
        ref: '1557cd8e237c436546a04e73f3518e31286e80a2' #6 Oct 2019 before disruptive changes!
        path: libdragon
        fetch-depth: 0

    - name: Adjust and re-build libdragon SDK
      run: |
        # Copy the adjusted source into the /libdragon folder
        cp -f ./source/240psuite/N64/libdragonchanges/display.c ./libdragon/src
        cp -f ./source/240psuite/N64/libdragonchanges/graphics.c ./libdragon/src
        cp -f ./source/240psuite/N64/libdragonchanges/display.h ./libdragon/include
        cp -f ./source/240psuite/N64/libdragonchanges/font.h ./libdragon/include

        # Rebuild libdragon SDK for changed source
        cd ./libdragon
        # For the moment, just ignore warnings (although valid!)
        sed -i 's/-std=gnu99 -O2 -Wall -Werror/-std=gnu99 -O2 -Werror/g' Makefile
        make clean
        make libdragon
        make install
        # Install the SDK tools
        make tools-clean
        make tools
        make tools-install

    - name: Build ROM
      # working-directory: ${{ github.workspace }}/source/240psuite/N64/
      run: |
        # libdragon make
        cd ./source/240psuite/N64/
        # DEBUG_BENCHMARK
        make

    - name: "Upload built ROMs to artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: NINTENDO_64-ROM
        path: |
          ${{ github.workspace }}/**/240psuite/N64/*.z64
